name: fin_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  injectable: ^2.3.2
  envied: ^0.3.0+3
  get_it: ^7.6.4
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/Illustration.svg
    - assets/Stars.svg
